# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='full_size',
        ),
    ]
